version: "3.3"
services:
  backend:
    image: node:lts-alpine
    expose:
      - "3001"
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/src
    working_dir: /src
    environment:
      NODE_ENV: development
    command: "npm run dev"
    tty: true
  frontend:
    image: node:lts-alpine
    expose:
      - "3000"
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/src
    working_dir: /src
    environment:
      NODE_ENV: development
      BACKEND_HOST: backend:3001
    command: "npm run dev"
    tty: true
